config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  get '/sessions/init', to: 'sessions#init'
  get '/sessions/login', to: 'sessions#login'

  post "/graphql", to: "graphql#execute"

  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql" if Rails.env.development?

  namespace :api do
    resource :search, only: [:show]
    resource :onboarding, only: [:show]
    resource :blog, only: [:show]
    resources :users, only: %i[show update] do
      collection do
        get :search
        get :verify_token
      end
    end
    resources :teams, only: %i[index show update] do
      collection do
        get :root
        get :search
      end
    end
    resources :tags, only: %i[show index update], constraints: { id: /[äöüß\w\-.:& $%]+/ }, format: false do
      get :search, on: :collection
    end

    resources :locations, only: %i[show index] do
      resources :rooms, only: [:show], constraints: { id: /[\w\-.20%]+/ }, format: false
    end

    get '/meta/users', to: 'meta#users'
    get '/meta/changes', to: 'meta#changes'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @graphql_schema = File.read(GeekosSchema::SCHEMA_FILE)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h2>API backend for Geekos</h2>

<h3>REST API</h3>

<a href="<%= api_search_path(q: 'test') %>">/api/search?q=search_term</a> - Global search (users + teams)
<br /><br />

<a href="<%= api_onboarding_path %>">/api/onboarding</a> - Onboarding Information
<br /><br />

<a href="<%= api_teams_path %>">/api/teams</a> - All teams
<br />
<a href="<%= api_team_path(OrgUnit.last.try(:id) || '123') %>">/api/teams/&lt;teamid&gt;</a> - Single team
<br />
<a href="<%= root_api_teams_path %>">/api/teams/root</a> - Team tree, starting with root team
<br />
<a href="<%= search_api_teams_path(q: 'scc') %>">/api/teams/search?q=search_term</a> - Search teams
<br /><br />

<a href="<%= api_user_path(User.last.try(:employeenumber) || '21868') %>">/api/users/:id</a> - User details
<br />
<a href="<%= search_api_users_path(q: 'test') %>">/api/users/search?q=search_term</a> - Search users
<br /><br />

<a href="<%= api_locations_path %>">/api/locations</a> - Office locations
<br />
<a href="<%= api_location_path(id: '7') %>">/api/locations/:floor_id</a> - Users in one location
<br />
<a href="<%= api_location_room_path(location_id: '1', id: '1.2.7') %>">/api/locations/:floor_id/rooms/:floor_room_number</a> - Users in one room
<br /><br />

<a href="<%= api_tags_path %>">/api/tags</a> - List tags
<br />
<a href="<%= api_tag_path(id: Tag.last.try(:name) || 'test') %>">/api/tag/&lt;name&gt;</a> - Show tag
<br />
<a href="<%= search_api_tags_path(q: Tag.last.try(:name) || 'test') %>">/api/tags/search?q=&lt;name&gt;</a> - Search tags
<br /><br />

<a href="<%= api_meta_users_path %>">/api/meta/users</a> - List user stats, new users etc.
<br />
<a href="<%= api_meta_changes_path %>">/api/meta/changes</a> - List changes (admin only)
<br />

<h3>GraphQL API</h3>

<style>
  pre {
    background-color: #c0c0c0;
    margin: 10px;
    padding: 10px
  }
</style>

<% if Rails.env.development? %>
Graphql browser: <a href="/graphiql">/graphiql</a>
<% end %>

<h4>GraphQL Schema</h4>

<pre>
<%= @graphql_schema %>
</pre>

<h4>Queries</h4>

User details:
<pre>
curl 'http://localhost:3000/graphql' \
  -X POST \
  -H 'content-type: application/json' \
  --data '{
   "query": "{ user (ident: \"tschmidt\") { email title picture (size: 100) githubUsernames trelloUsername leadOfOrgUnit { name } } }"
          }' | jq
</pre>

<h4>Mutations</h4>

Update user:
<pre>
curl 'http://localhost:3000/graphql' \
  -X POST \
  -H 'content-type: application/json' \
  -H 'Authorization: Token token=<your_auth_token>' \
  --data '{
    "query": "mutation { updateUser (ident: \"tschmidt\" title: \"Rocker\") { fullname email title } }"
          }' | jq
</pre>